###
services:
  # https://github.com/vercel/ai-chatbot
  # https://vercel.com/guides/does-vercel-support-docker-deployments
  ask:
    image: openaide/ask
    build:
      context: ./
      dockerfile: Dockerfile
      # target: builder
      platforms:
        - linux/amd64
        - linux/arm64
    command: ["node", "server.js"]
    # NEXT_DEBUG=true pnpm dev
    # command: ["pnpm", "dev"]
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-"gpt-4"}
      # Generate a random secret: `openssl rand -base64 32`
      - AUTH_SECRET=${AUTH_SECRET}
      #
      - KV_URL=
      # - KV_REST_API_URL=http://localhost:8079
      - KV_REST_API_URL=http://srh:8080
      - KV_REST_API_TOKEN=no_token
      - KV_REST_API_READ_ONLY_TOKEN=
      # - NEXTAUTH_URL=http://localhost:30001
      - NEXT_DEBUG=true
    # ports:
    #   - 3000:3000
    restart: always
    networks:
      - openland
    labels:
      - traefik.enable=true
      - traefik.docker.network=openland
      - traefik.http.routers.ask.rule=Host(`ask.openaide.localhost`)
      - traefik.http.routers.ask.entrypoints=web
      - traefik.http.services.ask.loadbalancer.server.port=3000
      - custom.traefik.group=openaide

##
networks:
  openland:
    external: true

###